import type { AutomationSchedule, AutomationStatus, Dialog, LogEntry, Settings, TelegramStatus, Template } from '../types'

const configuredBase = import.meta.env.VITE_API_URL?.replace(/\/$/, '')
export const API_BASE = configuredBase || (import.meta.env.DEV ? 'http://localhost:8000/api' : '/api')
class ApiError extends Error { constructor(message:string, public status:number){super(message)} }
async function request<T>(path:string, options?:RequestInit):Promise<T>{
  let response:Response
  try { response = await fetch(`${API_BASE}${path}`, {credentials:'include', headers:{'Content-Type':'application/json', ...options?.headers}, ...options}) }
  catch { throw new ApiError('Backend is unavailable. Start it and try again.', 0) }
  if(response.status===204) return undefined as T
  const data = await response.json().catch(()=>({detail:'The server returned an invalid response.'}))
  if(!response.ok){const detail=Array.isArray(data.detail)?data.detail.map((item:{msg?:string})=>item.msg||'Invalid request').join(' '):data.detail;throw new ApiError(typeof detail==='string'?detail:'Request failed.', response.status)}
  return data
}
const body=(value:unknown)=>JSON.stringify(value)
export const api={contact:()=>request<{telegram_username:string}>('/licenses/contact'),updateAdminContact:(telegram_username:string)=>request<{telegram_username:string}>('/licenses/admin/contact',{method:'PUT',body:body({telegram_username})}),
  health:()=>request<{status:string}>('/health'), meStatus:()=>request<{user_id:string;telegram:TelegramStatus;automation:AutomationStatus}>('/me/status'), appLogout:()=>request<{logged_out:boolean}>('/me/logout',{method:'POST'}), settings:()=>request<Settings>('/settings'), saveSettings:(api_id:string,api_hash:string)=>request<Settings>('/settings',{method:'PUT',body:body({api_id,api_hash})}),
  telegramStatus:()=>request<TelegramStatus>('/telegram/status'), sendCode:(phone:string)=>request<{status:string}>('/telegram/send-code',{method:'POST',body:body({phone})}), verifyCode:(code:string)=>request<{status:string}>('/telegram/verify-code',{method:'POST',body:body({code})}), verifyPassword:(password:string)=>request<{status:string}>('/telegram/verify-password',{method:'POST',body:body({password})}), reconnect:()=>request<TelegramStatus>('/telegram/reconnect',{method:'POST'}), logout:()=>request('/telegram/logout',{method:'POST'}), dialogs:()=>request<{items:Dialog[]}>('/telegram/dialogs'), sendOnce:(chat_ids:string[],message:string)=>request<{status:string;sent_count:number;failed_count:number}>('/telegram/send-message',{method:'POST',body:body({chat_ids,message})}),
  templates:()=>request<{items:Template[]}>('/messages'), createTemplate:(name:string,content:string)=>request<Template>('/messages',{method:'POST',body:body({name,content})}), updateTemplate:(id:string,name:string,content:string)=>request<Template>(`/messages/${id}`,{method:'PUT',body:body({name,content})}), deleteTemplate:(id:string)=>request(`/messages/${id}`,{method:'DELETE'}),
 automationStatus:()=>request<AutomationStatus>('/automation/status'), start:(chat_ids:string[],message:string,interval_seconds:number,license_key:string,schedule:AutomationSchedule)=>request<AutomationStatus>('/automation/start',{method:'POST',body:body({chat_ids,message,interval_seconds,license_key,...schedule})}), stop:()=>request<AutomationStatus>('/automation/stop',{method:'POST'}), pause:()=>request<AutomationStatus>('/automation/pause',{method:'POST'}), resume:()=>request<AutomationStatus>('/automation/resume',{method:'POST'}), logs:()=>request<{items:LogEntry[]}>('/automation/logs?limit=150'), validateLicense:(key:string)=>request<{valid:boolean;expires_at:string}>('/licenses/validate',{method:'POST',body:body({key})}), verifyAdmin:(code:string)=>request<{authenticated:boolean}>('/licenses/admin/verify',{method:'POST',body:body({code})}), adminLogout:()=>request<{logged_out:boolean}>('/licenses/admin/logout',{method:'POST'}), listLicenses:()=>request<{items:Array<{id:string;key:string|null;key_hint:string|null;starts_at:string;expires_at:string;active:boolean;duration_value?:number;duration_unit?:'hours'|'days';start_date?:string;end_date?:string}>}>('/licenses/admin/list'), revokeLicense:(id:string)=>request<{revoked:boolean}>(`/licenses/admin/${id}`,{method:'DELETE'}), generateLicense:(payload:{duration_value?:number;duration_unit?:'hours'|'days';start_date?:string;end_date?:string})=>request<{id:string;key:string;starts_at:string;expires_at:string;duration_value?:number;duration_unit?:'hours'|'days';start_date?:string;end_date?:string}>('/licenses/admin/generate',{method:'POST',body:body(payload)})
}
