import { ArrowLeft, ArrowRight, Download, PlugZap } from 'lucide-react'
import { API_BASE } from '../services/api'

function TelegramMark({size=18}:{size?:number}){return <svg width={size} height={size} viewBox="0 0 24 24" aria-hidden="true"><path fill="currentColor" d="M21.63 3.24 2.74 10.53c-1.29.52-1.28 1.24-.24 1.56l4.85 1.51 1.86 5.72c.23.63.12.88.77.88.5 0 .72-.23 1-.51l2.33-2.27 4.83 3.58c.89.49 1.53.24 1.75-.83l3.18-14.96c.32-1.3-.5-1.9-1.4-1.47ZM8.04 13.25l10.98-6.92c.54-.33 1.04-.15.63.22l-9.05 8.15-.35 3.76-2.21-5.21Z"/></svg>}

export function ApiDocs({home,openWorkspace}:{home:()=>void;openWorkspace:()=>void}){
 const displayBase=API_BASE.startsWith('http')?API_BASE:`${window.location.origin}${API_BASE}`
 const endpoints=[['GET','/api/health','Live service, Telegram connection, automation state, and uptime.'],['GET','/api/ready','Readiness check for Telegram and license configuration.'],['GET','/api/metrics','Compact operational counters for monitoring.'],['GET','/api/telegram/dialogs','List writable groups and channels.'],['POST','/api/automation/start','Start a scheduled multi-destination automation run.'],['POST','/api/automation/stop','Stop the active automation job.'],['GET','/api/automation/deliveries','Read persistent delivery history.'],['POST','/api/licenses/validate','Validate a 12-digit access key before starting.']]
 const payload=JSON.stringify({chat_ids:['-100123456789'],message:'Weekly update',interval_seconds:3600,license_key:'123456789012',active_weekdays:[0,1,2,3,4,5,6],max_messages:10},null,2)
 return <div className="docs-shell"><header className="docs-nav"><button className="docs-brand" onClick={home}><span className="home-logo"><TelegramMark/></span><span><b>TELE</b><small>AUTOMATION</small></span></button><div><button onClick={home}><ArrowLeft size={15}/> Homepage</button><button className="docs-nav-cta" onClick={openWorkspace}>Open workspace <ArrowRight size={15}/></button></div></header><main><section className="docs-hero"><div className="home-section-label">Developer reference</div><h1>API documentation for<br/><em>reliable delivery.</em></h1><p>Use the API to connect Telegram, configure automation, inspect runs, and monitor system health.</p><div className="docs-meta"><span><PlugZap size={15}/> Base URL</span><code>{displayBase}</code></div></section><section className="docs-layout"><aside><span>On this page</span><a href="#quickstart">Quick start</a><a href="#endpoints">Endpoints</a><a href="#payload">Start payload</a><a href="#errors">Errors</a></aside><div className="docs-content"><section id="quickstart"><div className="docs-kicker">01 / Quick start</div><h2>Connect, authorize, automate.</h2><p>Save Telegram API credentials in Settings, complete the Telegram sign-in flow, then call the automation endpoints from your client.</p><div className="docs-code"><span># inspect health on the current deployment</span><b>curl {displayBase}/health</b></div></section><section id="endpoints"><div className="docs-kicker">02 / Endpoints</div><h2>Core routes</h2><div className="endpoint-list">{endpoints.map(([method,path,description])=><div className="endpoint-row" key={path}><span className={'method method-'+method.toLowerCase()}>{method}</span><code>{path}</code><p>{description}</p></div>)}</div></section><section id="payload"><div className="docs-kicker">03 / Start payload</div><h2>Schedule a delivery</h2><pre className="docs-code docs-json">{payload}</pre></section><section id="errors"><div className="docs-kicker">04 / Errors</div><h2>Predictable responses</h2><p>Validation failures return <code>422</code>, invalid license keys return <code>403</code>, conflicting jobs return <code>409</code>, and rate limits return <code>429</code> with a Retry-After header.</p></section></div></section></main><footer className="docs-footer"><span>Tele Automation API</span><span>Developed by Abby</span></footer></div>
}
